export enum SongActions {
    GET_SONGS_REQUESTED = 'GET_SONGS_REQUESTED',
    EDIT_SONG_REQUESTED = 'EDIT_SONG_REQUESTED',
    DELETE_SONG_REQUESTED = 'DELETE_SONG_REQUESTED',
    ADD_SONG_REQUESTED = 'ADD_SONG_REQUESTED',
    SERCH_SONG_REQUESTED = 'SERCH_SONG_REQUESTED'
}

export enum StatsActions {
    GET_STATS_REQUESTED = 'GET_STATS_REQUESTED',
}
