export enum SongActions {
    GET_SONGS_REQUESTED = 'GET_SONGS_REQUESTED',
    UPDATE_SONG_REQUESTED = 'UPDATE_SONG_REQUESTED',
    DELETE_SONG_REQUESTED = 'DELETE_SONG_REQUESTED',
    ADD_SONG_REQUESTED = 'ADD_SONG_REQUESTED',
    SEARCH_SONG_REQUESTED = 'SEARCH_SONG_REQUESTED',
    GET_SONG_DETAILS_REQUESTED = 'GET_SONG_DETAILS_REQUESTED'
}

export enum StatsActions {
    GET_STATS_REQUESTED = 'GET_STATS_REQUESTED',
}

export enum AlbumActions {
    GET_ALBUMS_REQUESTED = 'GET_ALBUMS_REQUESTED',
}

export enum ArtistActions {
    GET_ARTISTS_REQUESTED = 'GET_ARTIGET_ARTISTS_REQUESTEDSTS_REQUESTED',
}

export enum GenreActions {
    GET_GENRES_REQUESTED = 'GET_GENRES_REQUESTED',
}
