export enum SongActions {
    GET_SONGS_REQUESTED = 'GET_SONGS_REQUESTED',
    UPDATE_SONG_REQUESTED = 'UPDATE_SONG_REQUESTED',
    DELETE_SONG_REQUESTED = 'DELETE_SONG_REQUESTED',
    ADD_SONG_REQUESTED = 'ADD_SONG_REQUESTED',
    SERCH_SONG_REQUESTED = 'SERCH_SONG_REQUESTED',
    GET_SONG_DETAILS_REQUESTED = 'GET_SONG_DETAILS_REQUESTED'
}

export enum StatsActions {
    GET_STATS_REQUESTED = 'GET_STATS_REQUESTED',
}
